version: '3.1'

services:
  node:
    container_name: nodetube
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "49161:3000"
    volumes:
      - nodetube_node_modules:/app/node_modules
      - nodetube_upload:/app/upload
      - nodetube_uploads:/app/uploads
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://nodetube-mongo:27017/nodetube
    depends_on:
      - redis
      - mongo
    command: npm start
    networks:
      - nodetube-network

  mongo:
    container_name: nodetube-mongo
    image: mongo:4.4
    volumes:
      - nodetube_db:/data/db
    expose:
      - "27017"
    networks:
      - nodetube-network

  redis:
    container_name: nodetube-redis
    image: redis
    networks:
      - nodetube-network

volumes:
  nodetube_node_modules:
    driver: local
  nodetube_upload:
    driver: local
  nodetube_uploads:
    driver: local
  nodetube_db:
    driver: local

networks:
  nodetube-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
